version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-patch
