version: 2
sources:
  - name: raw_databricks_workflow_monitoring
    description: Raw data from databricks for databricks monitoring analysis.
    database: "{{ var('dag_monitoring_databricks_database', '')}}"
    schema: "{{ var('dbt_dag_monitoring_tests', 'dag_monitoring_databricks_schema' ) }}"
    tables:
      - name: job_runs
        description: Table that contains the execution data of the Databricks
          pipelines(jobs)
        columns:
          - name: run_id
            description: Unique identifier of the table. Job run id
            tests:
              - not_null
              - unique
          - name: job_id
            description: Job id.
          - name: trigger
            description: It tells how the pipeline execution was triggered.
          - name: start_time
            description: Timestamp when the DAG execution started.
          - name: end_time
            description: Timestamp when the DAG execution ended.
          - name: execution_duration
            description: Duration of DAG in milliseconds.
          - name: run_type
            description: Type of execution
          - name: tasks
            description: '{{ doc("tasks_doc") }}'
            data_type: struct