name: 'dbt_dag_monitoring'
version: '0.2.0'

require-dbt-version: [">=1.3.0", "<2.0.0"]

config-version: 2

target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]
macro-paths: ["macros"]
log-path: "logs"

profile: dbt_dag_monitoring

sources:
  adf_sources:
    raw_adf_monitoring:
      +enabled: false
  databricks_workflow_sources:
    raw_databricks_workflow_monitoring:
      +enabled: true
  airflow_sources:
    raw_airflow_monitoring:
      +enabled: false

models:
  dbt_dag_monitoring:
    marts:
      +materialized: table
    staging:
      +materialized: view
      +schema: dev_laysa_bitencourt

vars:
  dbt_dag_monitoring:
    enabled_sources: ['databricks_workflow'] #Possible values: 'airflow', 'adf' or 'databricks_workflow'
    dag_monitoring_start_date: cast('2023-01-01' as date)
    dag_monitoring_airflow_database: #landing_zone
    dag_monitoring_airflow_schema: #airflow_metadata
    dag_monitoring_databricks_database: caixa-demo-core_main
    dag_monitoring_databricks_schema: raw_monitoring
    dag_monitoring_adf_database: #raw
    dag_monitoring_adf_schema: #adf_metadata