dbt_dag_monitoring:
    target: "{{ env_var('DBT_DEFAULT_TARGET', 'databricks')}}"
    outputs:
        databricks: 
            type: databricks
            catalog: "{{ env_var('DEV_CATALOG_NAME')}}"
            schema: "{{ env_var('DEV_SCHEMA_NAME')}}"
            host: "{{ env_var('DEV_HOST') }}"
            http_path: "{{ env_var('DEV_HTTP_PATH') }}"
            token: "{{ env_var('DEV_TOKEN') }}"
            threads: 16
            ansi_mode: false
        
        bigquery:
            dataset: "{{ env_var('BIGQUERY_DATASET') }}"
            project: "{{ env_var('BIGQUERY_PROJECT') }}"
            job_execution_timeout_seconds: "{{ env_var('DBT_JOB_TIMEOUT') | int }}"
            threads: "{{ env_var('DBT_THREADS') | int }}"
            job_retries: "{{ env_var('DBT_JOB_RETRIES') | int }}"
            method: oauth
            location: us
            priority: interactive
            type: bigquery