dbt_dag_monitoring:
    target: "{{ env_var('DBT_DEFAULT_TARGET', 'databricks')}}"
    outputs:
        databricks: 
            type: databricks
            catalog: "{{ env_var('DEV_CATALOG_NAME')}}"
            schema: "{{ env_var('DEV_SCHEMA_NAME')}}"
            host: "{{ env_var('DEV_HOST') }}"
            http_path: "{{ env_var('DEV_HTTP_PATH') }}"
            token: "{{ env_var('DEV_TOKEN') }}"
            threads: 16
            ansi_mode: false

         snowflake:
            type: snowflake
            account: "{{ env_var('SNOWFLAKE_TEST_ACCOUNT') }}"
            user: "{{ env_var('SNOWFLAKE_TEST_USER') }}"
            password: "{{ env_var('SNOWFLAKE_TEST_PASSWORD') }}"
            role: "{{ env_var('SNOWFLAKE_TEST_ROLE') }}"
            database: "{{ env_var('SNOWFLAKE_TEST_DATABASE') }}"
            warehouse: "{{ env_var('SNOWFLAKE_TEST_WAREHOUSE') }}"
            schema: codegen_integration_tests_snowflake
            threads: 1