name: 'dbt_dag_monitoring_tests'
version: '0.2.0'

require-dbt-version: [">=1.0.0", "<2.0.0"]

config-version: 2

target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]
macro-paths: ["macros"]
log-path: "logs"

profile: dbt_dag_monitoring_tests

models:
  dbt_dag_monitoring_tests:
    staging:
      +materialized: view

sources:
 dbt_dag_monitoring:
   +enabled: true
 events:
   airflow_sources:
     +enabled: false                # true or false
   adf_sources:
     +enabled: false                # true or false
   databricks_workflow_sources:
     +enabled: true                 # true or false

vars:
 dbt_dag_monitoring_tests:
   enabled_sources: ['databricks_workflow']
   dag_monitoring_start_date: cast('2023-01-01' as date)
   dag_monitoring_airflow_database: landing_zone
   dag_monitoring_airflow_schema: airflow_metadata
   dag_monitoring_databricks_database: caixa-demo-core_main
   dag_monitoring_databricks_schema: raw
   dag_monitoring_adf_database: raw
   dag_monitoring_adf_schema: adf_metadata
