name: 'dbt_dag_monitoring_integration_tests'
version: '0.2.0'

require-dbt-version: [">=1.0.0", "<2.0.0"]

config-version: 2

target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]
macro-paths: ["macros"]
log-path: "logs"
seed-paths: ["seeds"] 

profile: dbt_dag_monitoring_integration_tests

dispatch:
  - macro_namespace: 'dbt_utils'
    search_order: ['dbt_utils_integration_tests', 'dbt_utils']

sources:
  dbt_dag_monitoring:
    staging:
      adf_sources:
        raw_adf_monitoring:
          +enabled: false
      databricks_workflow_sources:
        raw_databricks_workflow_monitoring:
          +enabled: false
      airflow_sources:
        raw_airflow_monitoring:
          +enabled: true

models:
  dbt_dag_monitoring:
    marts:
      +materialized: table
    staging:
      adf_sources:  
        +enabled: false
      airflow_sources:
        +enabled: true
      databricks_workflow_sources:
        +enabled: false
      +materialized: view

vars:
  dbt_dag_monitoring:
    enabled_sources: ['airflow'] #Possible values: 'airflow', 'adf' or 'databricks_workflow'
    dag_monitoring_start_date: cast('2023-01-01' as date)
    dag_monitoring_airflow_database: cdi_dev
    dag_monitoring_airflow_schema: dev_laysa_bitencourt
    dag_monitoring_databricks_database: cdi_dev
    dag_monitoring_databricks_schema: dev_laysa_bitencourt
    dag_monitoring_adf_database: cdi_dev
    dag_monitoring_adf_schema: ci_dbt_dag_monitoring