name: 'dbt_dag_monitoring_integration_tests'
version: '0.2.0'

require-dbt-version: [">=1.0.0", "<2.0.0"]

config-version: 2

target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]
macro-paths: ["macros"]
log-path: "logs"
seed-paths: ["seeds"] 

profile: dbt_dag_monitoring_integration_tests

dispatch:
  - macro_namespace: 'dbt_utils'
    search_order: ['dbt_utils_integration_tests', 'dbt_utils']

sources:
  dbt_dag_monitoring_tests:
    staging:
      adf_sources:
        raw_adf_monitoring:
          +enabled: false
      databricks_workflow_sources:
        raw_databricks_workflow_monitoring:
          +enabled: true
      airflow_sources:
        raw_airflow_monitoring:
          +enabled: false

vars:
  dbt_dag_monitoring_tests:
    enabled_sources: ['databricks_workflow_sources']
    dag_monitoring_start_date: cast('2023-01-01' as date)
    dag_monitoring_airflow_database: landing_zone
    dag_monitoring_airflow_schema: airflow_metadata
    dag_monitoring_databricks_database: cdi_dev
    dag_monitoring_databricks_schema: ci_dbt_dag_monitoring
    dag_monitoring_adf_database: cdi_dev
    dag_monitoring_adf_schema: ci_dbt_dag_monitoring
