name: 'dbt_dag_monitoring_integration_tests'
version: '0.2.0'

require-dbt-version: [">=1.0.0", "<2.0.0"]

config-version: 2

target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]
macro-paths: ["macros"]
log-path: "logs"
seed-paths: ["seeds"] 

profile: dbt_dag_monitoring_integration_tests

dispatch:
  - macro_namespace: 'dbt_utils'
    search_order: ['dbt_utils_integration_tests', 'dbt_utils']

