dbt_dag_monitoring_integration_tests:
  target: '{{ env_var(''DBT_DEFAULT_TARGET'', ''databricks'')}}'
  outputs:
    databricks:
      ansi_mode: false
      catalog: '{{ env_var(''DEV_CATALOG_NAME'')}}'
      host: '{{ env_var(''DEV_HOST'') }}'
      http_path: '{{ env_var(''DEV_HTTP_PATH'') }}'
      schema: '{{ env_var(''DEV_SCHEMA_NAME'')}}'
      threads: 16
      token: '{{ env_var(''DEV_TOKEN'') }}'
      type: databricks

    bigquery:
      dataset: "{{ env_var('BIGQUERY_DATASET') }}"
      project: "{{ env_var('BIGQUERY_PROJECT') }}"
      job_execution_timeout_seconds: "{{ env_var('DBT_JOB_TIMEOUT') | int }}"
      threads: "{{ env_var('DBT_THREADS') | int }}"
      job_retries: "{{ env_var('DBT_JOB_RETRIES') | int }}"
      method: oauth
      location: us
      priority: interactive
      type: bigquery

    snowflake:
      type: "snowflake"
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
      threads: 10
