version: 2

models:
  - name: test
    tests:
      - dbt_utils.equality:
          compare_model: source('raw_databricks_workflow_monitoring', 'job_runs')
          exclude_columns: 
            - cleanup_duration 
            - creator_user_name
            - job_clusters
            - number_in_job
            - original_attempt_run_id
            - run_duration
            - run_name
            - run_page_url
            - setup_duration
            - state
            - InsertedDate
            - number_in_job
            - original_attempt_run_id
            - schedule
            - setup_duration
            
