name: CI

# on:
#   pull_request:
#     types:
#       - opened
#     branches:
#       - main

on:
    push:
        branches:
        - feature/how-to-test      

env:
    DBT_PROFILES_DIR: ${{ github.workspace }}
    DBT_DEFAULT_TARGET: dev
    DEV_CATALOG_NAME: caixa-demo-core_main
    DEV_SCHEMA_NAME: raw
    DEV_HOST: ${{ secrets.DATABRICKS_HOST }}
    DEV_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
    DEV_HTTP_PATH: ${{ secrets.HTTP_PATH }}


jobs:
  dbt-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run dbt debug
        run: dbt debug

      - name: dbt deps
        run: dbt deps

      - name: dbt compile
        run: dbt compile