name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main   

env:
    DBT_PROFILES_DIR: ${{ github.workspace }}
    DBT_DEFAULT_TARGET: databricks
    DEV_CATALOG_NAME: cdi_dev
    DEV_SCHEMA_NAME: ci_dbt_dag_monitoring
    DEV_HOST: ${{ secrets.DATABRICKS_HOST }}
    DEV_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
    DEV_HTTP_PATH: ${{ secrets.HTTP_PATH }}

    BIGQUERY_DATASET: ci_dbt_dag_monitoring
    BIGQUERY_PROJECT: indicium-sandbox
    DBT_JOB_TIMEOUT: 300
    DBT_THREADS: 16
    DBT_JOB_RETRIES: 1


jobs:
  dbt-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Authenticate to GCP
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.BIGQUERY_AUTH }}"

      - name: Run dbt debug for Databricks
        run: dbt debug 
      
      - name: Run dbt debug for BigQuery
        run: dbt debug --target bigquery

      - name: dbt deps
        run: dbt deps

      - name: dbt compile
        run: dbt compile

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: enter integration tests
        run: |
          cd integration_tests/

      - name: Authenticate to GCP
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.BIGQUERY_AUTH }}"
      
      - name: Run dbt integration tests Databricks source in Databricks connection
        env:
          DBT_PROFILES_DIR: ${{ github.workspace }}/integration_tests
          DBT_PROJECT_DIR: ${{ github.workspace }}/integration_tests
        run: |
          dbt deps --target databricks
          
          dbt run-operation create_schema --args '{schema_name: ci_dbt_dag_monitoring}' --target databricks

          dbt seed --target databricks
          
          dbt run-operation jobs --target databricks
          dbt run-operation job_runs --target databricks
          
          dbt test -s source:* --target databricks
          
          dbt build --target databricks

      - name: switch enabled sources for adf source
        run: |
          cd ${{ github.workspace }}
          . change_dbt_project_adf_source.sh
          cd integration_tests/

      - name: Run dbt tasks for ADF source in Databricks connection
        env:
          DBT_PROFILES_DIR: ${{ github.workspace }}/integration_tests
          DBT_PROJECT_DIR: ${{ github.workspace }}/integration_tests
        run: |
          dbt deps

          dbt seed --target databricks

          dbt run-operation adf_pipeline_runs --target databricks
          dbt run-operation adf_triggers --target databricks

          dbt test -s source:* --target databricks

          dbt build --target databricks

      - name: switch enabled sources for airflow source 
        run: |
          cd ${{ github.workspace }}
          . change_dbt_project_airflow_source.sh
          cd integration_tests/

      - name: Run dbt tasks for Airflow source in Databricks connection
        env:
          DBT_PROFILES_DIR: ${{ github.workspace }}/integration_tests
          DBT_PROJECT_DIR: ${{ github.workspace }}/integration_tests
        run: |
          dbt deps

          dbt seed --target databricks

          dbt test -s source:* --target databricks

          dbt build --target databricks

          dbt run-operation drop_schema --args '{schema_name: ci_dbt_dag_monitoring}'

      - name: change databricks database to bigquery database
        run: |
          cd ${{ github.workspace }}
          sed -i 's/dag_monitoring_databricks_database: cdi_dev/dag_monitoring_databricks_database: indicium-sandbox/' dbt_project.yml
          . change_dbt_project_databricks_source.sh
          cd integration_tests/

      - name: Run dbt integration tests Databricks source in BigQuery connection
        env:
          DBT_PROFILES_DIR: ${{ github.workspace }}/integration_tests
          DBT_PROJECT_DIR: ${{ github.workspace }}/integration_tests
        run: |
          dbt deps --target bigquery
          
          dbt run-operation create_schema --args '{schema_name: ci_dbt_dag_monitoring}' --target bigquery

          dbt run-operation jobs --target bigquery
          dbt run-operation job_runs --target bigquery
          
          dbt test -s source:* --target bigquery
          
          dbt build --exclude-resource-type seed --target bigquery

      - name: switch enabled sources for adf source
        run: |
          cd ${{ github.workspace }}
          sed -i 's/dag_monitoring_adf_database: cdi_dev/dag_monitoring_adf_database: indicium-sandbox/' dbt_project.yml
          . change_dbt_project_adf_source.sh
          cd integration_tests/

      - name: Run dbt integration tests ADF source in BigQuery connection
        env:
          DBT_PROFILES_DIR: ${{ github.workspace }}/integration_tests
          DBT_PROJECT_DIR: ${{ github.workspace }}/integration_tests
        run: |
          dbt deps

          dbt seed -s adf_pipelines --target bigquery

          dbt run-operation adf_activity_runs --target bigquery
          dbt run-operation adf_pipeline_runs --target bigquery
          dbt run-operation adf_triggers --target bigquery

          dbt test -s source:* --target bigquery

          dbt build --exclude-resource-type seed --target bigquery
      
      - name: switch enabled sources for airflow source 
        run: |
          cd ${{ github.workspace }}
          . change_dbt_project_airflow_source.sh
          cd integration_tests/

      - name: Run dbt tasks for Airflow source in BigQuery connection
        env:
          DBT_PROFILES_DIR: ${{ github.workspace }}/integration_tests
          DBT_PROJECT_DIR: ${{ github.workspace }}/integration_tests
        run: |
          dbt deps

          dbt seed --target bigquery

          dbt run-operation seed__dag_run --target bigquery
          dbt run-operation seed__dag --target bigquery
          dbt run-operation seed__task_fail --target bigquery
          dbt run-operation seed__task_instance --target bigquery

          dbt test -s source:* --target bigquery

          dbt build --target bigquery

          dbt run-operation drop_schema --args '{schema_name: ci_dbt_dag_monitoring}'

