name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main   

env:
    DBT_PROFILES_DIR: ${{ github.workspace }}
    DBT_DEFAULT_TARGET: databricks
    DEV_CATALOG_NAME: caixa-demo-core_dev
    DEV_SCHEMA_NAME: dev_laysa_bitencourt
    DEV_HOST: ${{ secrets.DATABRICKS_HOST }}
    DEV_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
    DEV_HTTP_PATH: ${{ secrets.HTTP_PATH }}


jobs:
  dbt-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run dbt debug
        run: dbt debug

      - name: dbt deps
        run: dbt deps

      - name: dbt compile
        run: dbt compile

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # - name: enter integration tests
      #   run: |
      #     cd integration_tests/

      # - name: set up dbt profile

      # - name: dbt seed for Databricks
      #   run: dbt seed --target databricks

      # - name: dbt build for Databricks
      #   run: dbt run --target databricks

      